* Taconic Security Hub

A Nixos flake providing modules and example configuration for a server providing basic security services for small organizations.

  - Unified Observability
  - Unified Logging
  - Network Monitoring
  - WireGuard VPN For Administrators
  - Off-host, Encypted Backups

The module configuration is structured as a hierarchy.  Each sub-module has an `enable` option

- taconic
  - wireguard-vpn
  - network-monitor
  - log-server    
  - admin
  - nginx-proxy

* Deployment

See the  [[docs/operations.org][Operations Manual]]

* Development

** On NixOS

Using [[https://nixos.wiki/wiki/NixOS_Containers][Native NixOS Containers]] via the =nixos-container= command to manage the supplied =container= nixosConfiguration is the easiest path  This presumes a bridge network, defaulting to incusbr0, but doesn't use incus.  The Makefile can be update to reflect your development system.  Bridge networking is only needed if you want to test the services.

To build derivation for the container, but not instantiate an instance of it, the =build= target can be used.

#+begin_src shell
make build
#+end_src

To create a systemd managed container that you can run on your host, the =create= target can be used.  This presumes that

#+begin_src shell
make create
#+end_src

To start the container, the =start= target will start the systemd
container.  To get a root login, use the =root= target.

As you iterate, the =update= target will update the container.  You may need to use the =restart= target on occasion to restart it entirely.

* Acknowledgments

The log and metric services are based on the [[https://xeiaso.net/blog/prometheus-grafana-loki-nixos-2020-11-20/][How to Setup Prometheus, Grafana and Loki on NixOS]] article by [[https://xeiaso.net/][Xe Iaso]]
